name = "a0b_scd40"
description = "A0B: SCD40 CO2 sensor driver"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "scd40"]

project-files = ["gnat/a0b_scd40.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
a0b_time = "*"
a0b_i2c = "*"
a0b_timer = "*"
